apiVersion: v1
kind: ConfigMap
metadata:
  name: itsm-config
  namespace: itsm
data:
  POSTGRES_HOST: "psqlitsmac742.postgres.database.azure.com"
  POSTGRES_PORT: "5432"
  EUREKA_SERVER_URL: "http://eureka-server:8761/eureka/"
